config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :todo_items
  root to: 'todo_items#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  scope :unfinished, -> { where(done_at: nil) }
  scope :finished, -> { where("done_at IS NOT NULL") }

  validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  
    def index
        @finished_items = TodoItem.finished.order('done_at DESC')
        @todo_items = TodoItem.unfinished.order('created_at DESC')
      end
    
      private
    
      def todo_item_params
        params.require(:todo_item).permit(:title, :done_at)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    # @users = User.where("name LIKE ?", "%#{params[:query]}%")
    @users ||= User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todo_items/_todo_item.html.erb
<li class="py-4 px-2 hover:bg-gray-50 border-t border-gray-300">
    <div class="flex justify-between">
        <div>
            <%= check_box_tag "todo_item_item[done_at]" , "1" , todo_item.done_at.present?,
                id: "todo_item-done-#{todo_item.id}" ,
                data: { reflex: "change->TodoItemReflex#toggle_done" , id:todo_item.id }%>
        </div>
        <div class="w-2/5 <%= todo_item.done_at ? ' line-through' : '' %>">
            <%= todo_item.title %>
        </div>
        <div class="w-2/5">
            <%= check_box_tag "todo_item_item[completed_at]","1", todo_item.completed_at?,data: {reflex: "change->ExampleReflex#toggle", id: todo_item.id}%><br>
            <%= todo_item.completed_at %>
        </div>
        <div>
            <button data-reflex="click->TodoItemReflex#destroy" data-id="<%=todo_item.id%>">x</button>
        </div>
        
    </div>
</li>

app/views/todo_items/index.html.erb
<div class="max-w-none mx-auto mt-5">
    <div class="bg-white overflow-hidden shadow sm:rounded-lg text-xl">
        <div class="p-5">
            <%= form_for(TodoItem.new, class: "mt-2" , data: {controller: "todo-item" ,action: "submit->todo-item#create" }) do |f| %>
                <%=f.text_field :title, autofocus: true,class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-900 leading-tight focus:outline-none focus:shadow-outline", placeholder: "What needs to be done?" %>
            <% end %>
            <div class="text-gray-600">
                <ul class="mt-5" aria-disabled="true">
                    <% @todo_items.all.each do |todo_item| %>
                        <%= render todo_item %>
                    <% end %>
                </ul>
                <% if @finished_items.any? %>
                    <div class="border-t-2">
                        <h3 class="my-2">Done:</h3>
                        <ul>
                            <% @finished_items.all.each do |finished_item| %>
                                <%= render finished_item %>
                            <% end %>
                        </ul>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_search.html.erb
 <%= form_with(method: :get) do |form| %>
      <%= form.label :query, "Search by name:" %>
      <%= form.text_field :query, data: { action: "input->user-search#search" }, autocomplete: "off", value: params[:query] %>
    <% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= user.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this user', edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div data-controller="user-search">
   
    <%= form_with(method: :get, data: { reflex: "submit->UserSearch#search" }) do |form| %>
      <%= form.label :query, "Search by name:" %>
      <%= form.text_field :query, value: params[:query] %>
      <%= form.submit 'Search', name: nil %>
    <% end %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    </table>
  </div>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <% if @users.present?%>
      <%= render @users %>
    <% else %>
      No user found
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>